# Generated by Django 3.1.4 on 2021-01-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210107_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
