# Generated by Django 3.1.4 on 2021-01-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210107_0006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telefone',
            unique_together={('proprietario', 'telefone')},
        ),
    ]
